version: '3.8'

services:
  agent:
    build: ./agent
    env_file: ./agent/.env
    ports:
      - "${AGENT_PORT:-8000}:8000"
    depends_on:
      - bedrock-rag-mcp
      - mongodb-mcp
    networks:
      - mcp-network
    volumes:
      - ./agent/agent.py:/app/agent/agent.py
      - ./agent/app.py:/app/agent/app.py
      # Mount other specific files as needed
      - agent-data:/data
    command: >
      bash -c "python -m agent.app"

  bedrock-rag-mcp:
    build: ./mcp_servers/bedrock_rag
    env_file: ./mcp_servers/bedrock_rag/.env
    ports:
      - "${BEDROCK_RAG_PORT:-3003}:3003"
    networks:
      - mcp-network
    volumes:
      - ./mcp_servers/bedrock_rag/tools:/app/tools
      - ./mcp_servers/bedrock_rag/bedrockRag_mcp_server.py:/app/bedrockRag_mcp_server.py
      - bedrock-data:/app/data
    environment:
      # Server Settings
      - SERVER_HOST=0.0.0.0
      - BEDROCK_RAG_PORT=${BEDROCK_RAG_PORT:-3003}
      - DEBUG=${DEBUG:-False}
      
      # AWS Credentials
      # - AWS_REGION=${AWS_REGION:-ca-central-1}
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      
      # Knowledge Base Settings
      # - KNOWLEDGE_BASE_ID=${KNOWLEDGE_BASE_ID}
      
      # Reranking Settings
      - USE_RERANKING=${USE_RERANKING:-True}
      - RERANK_MODEL_ID=${RERANK_MODEL_ID:-amazon.rerank-v1:0}
      - INITIAL_RESULTS=${INITIAL_RESULTS:-5}
      - TOP_N_RESULTS=${TOP_N_RESULTS:-3}
      
      # Logging Settings
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Environment
      - ENVIRONMENT=${ENVIRONMENT:-development}
    command: >
      python bedrockRag_mcp_server.py --host 0.0.0.0

  mongodb-mcp:
    build: ./mcp_servers/mongodb
    env_file: ./mcp_servers/mongodb/.env
    ports:
      - "${MONGODB_MCP_PORT:-3004}:3004"
    networks:
      - mcp-network
    volumes:
      - ./mcp_servers/mongodb/tools:/app/tools
      - ./mcp_servers/mongodb/mongodb_mcp_server.py:/app/mongodb_mcp_server.py
    environment:
      # Server Settings
      - SERVER_HOST=0.0.0.0
      - MONGODB_MCP_PORT=${MONGODB_MCP_PORT:-3004}
      - DEBUG=${DEBUG:-False}
      
      # MongoDB Settings
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-bedrock_rag}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION:-conversations}
      - MAX_HISTORY_LENGTH=${MAX_HISTORY_LENGTH:-10}
      
      # Logging Settings
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    command: >
      python mongodb_mcp_server.py --host 0.0.0.0

networks:
  mcp-network:
    driver: bridge

volumes:
  agent-data:
  bedrock-data:
