version: '3.8'

services:
  agent:
    image: ${ECR_REPOSITORY:-bedrock-agent}/bedrock-agent:${VERSION:-latest}
    ports:
      - "${AGENT_PORT:-8000}:8000"
    depends_on:
      - bedrock-rag-mcp
      - mongodb-mcp
    networks:
      - mcp-network
    volumes:
      - agent-data:/data
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=${AGENT_PORT:-8000}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - AWS_REGION=${AWS_REGION:-ca-central-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BEDROCK_MODEL_ID=anthropic.claude-3-sonnet-20240229-v1:0
      - TEMPERATURE=0
      - MAX_TOKENS=3000
      - TOP_P=0.9
      - BEDROCK_RAG_MCP_HOST=bedrock-rag-mcp
      - BEDROCK_RAG_MCP_PORT=${BEDROCK_RAG_PORT:-3003}
      - MONGODB_MCP_HOST=mongodb-mcp
      - MONGODB_MCP_PORT=${MONGODB_MCP_PORT:-3004}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-bedrock_rag}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION:-conversations}
      - MAX_HISTORY_LENGTH=10
      - MAX_TOKEN_LIMIT=2000
      - LOG_LEVEL=INFO
    command: >
      bash -c "python -m agent.app"

  bedrock-rag-mcp:
    image: ${ECR_REPOSITORY:-bedrock-agent}/bedrock-rag-mcp:${VERSION:-latest}
    ports:
      - "${BEDROCK_RAG_PORT:-3003}:3003"
    networks:
      - mcp-network
    volumes:
      - bedrock-data:/app/data
    environment:
      - AWS_REGION=${AWS_REGION:-ca-central-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - KNOWLEDGE_BASE_ID=${KNOWLEDGE_BASE_ID}
      - SERVER_HOST=0.0.0.0
      - BEDROCK_RAG_PORT=${BEDROCK_RAG_PORT:-3003}
      - DEBUG=False
      - USE_RERANKING=True
      - RERANK_MODEL_ID=amazon.rerank-v1:0
      - INITIAL_RESULTS=5
      - TOP_N_RESULTS=3
      - LOG_LEVEL=INFO
      - AGENT_PORT=${AGENT_PORT:-8000}
      - API_HOST=0.0.0.0
      - ENVIRONMENT=${ENVIRONMENT:-development}
    command: >
      python bedrockRag_mcp_server.py --host 0.0.0.0

  mongodb-mcp:
    image: ${ECR_REPOSITORY:-bedrock-agent}/mongodb-mcp:${VERSION:-latest}
    ports:
      - "${MONGODB_MCP_PORT:-3004}:3004"
    networks:
      - mcp-network
    environment:
      - SERVER_HOST=0.0.0.0
      - MONGODB_MCP_PORT=${MONGODB_MCP_PORT:-3004}
      - DEBUG=false
      - LOG_LEVEL=INFO
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-bedrock_rag}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION:-conversations}
      - MAX_HISTORY_LENGTH=10
    command: >
      python mongodb_mcp_server.py --host 0.0.0.0

networks:
  mcp-network:
    driver: bridge

volumes:
  agent-data:
  bedrock-data:
