version: '3.8'

services:
  agent:
    image: ${ECR_REPOSITORY}/bedrock-rag-agent:${VERSION}
    container_name: bedrock-rag-agent
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BEDROCK_RAG_MCP_URL=http://bedrock-rag-mcp:3003
      - MONGODB_MCP_URL=http://mongodb-mcp:3004
      - LOG_LEVEL=INFO
    depends_on:
      - bedrock-rag-mcp
      - mongodb-mcp

  bedrock-rag-mcp:
    image: ${ECR_REPOSITORY}/bedrock-rag-mcp:${VERSION}
    container_name: bedrock-rag-mcp
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BEDROCK_MODEL_ID=anthropic.claude-3-sonnet-20240229-v1:0
      - LOG_LEVEL=INFO

  mongodb-mcp:
    image: ${ECR_REPOSITORY}/mongodb-mcp:${VERSION}
    container_name: mongodb-mcp
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bedrock_rag
      - LOG_LEVEL=INFO
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: 